parameters:
    reader:
        max_attempts: 5
        response_required_fields:
            base_currency_field: base
            rates_field: rates
    client:
        types:
            - business
            - private
    operation:
        types:
            - deposit
            - withdraw
    currency:
        base_currency_code: EUR
        supported:
            -   code: EUR
                scale: 2
            -   code: USD
                scale: 2
            -   code: JPY
                scale: 0
